# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u8fdb\u884c\u5230\u7684\u65e5\u671f')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=16)),
                ('date_of_birth', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u751f\u65e5')),
                ('join_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u8fdb\u5165\u65e5\u671f')),
                ('parent_mother', models.IntegerField(blank=True, default=0)),
                ('parent_father', models.IntegerField(blank=True, default=0)),
                ('dead', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6b7b\u4ea1')),
                ('date_of_dead', models.DateTimeField(blank=True, null=True, verbose_name='\u6b7b\u4ea1\u65e5\u671f')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
