# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0003_auto_20170721_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=16),
        ),
    ]
