# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0005_auto_20170811_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demand',
        ),
    ]
