# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0007_personcharacter_persondesire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillPerson',
            new_name='PersonSkill',
        ),
    ]
