# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0010_dolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolog',
            name='act_hour',
            field=models.IntegerField(default=0, verbose_name='\u884c\u4e3a\u5c0f\u65f6'),
        ),
    ]
