# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0012_auto_20170816_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='belong',
            new_name='person_id',
        ),
    ]
