# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0013_auto_20170816_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=0, verbose_name='\u7248\u6743\u6240\u6709\u4eba')),
                ('author', models.IntegerField(default=0, verbose_name='\u4f5c\u8005')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('score', models.IntegerField(default=0, verbose_name='\u8bc4\u5206')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=0, verbose_name='\u6240\u6709\u4eba')),
                ('author', models.IntegerField(default=0, verbose_name='\u4f5c\u8005')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('score', models.IntegerField(default=0, verbose_name='\u8bc4\u5206')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaintingProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(default=0, verbose_name='\u4f5c\u8005')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('work_hour', models.IntegerField(default=0, verbose_name='\u521b\u4f5c\u65f6\u957f')),
                ('effort', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='realestate',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
