# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0014_auto_20170816_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingprocess',
            name='uptime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 16, 16, 58, 9, 551000), verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
