# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkplanet', '0015_paintingprocess_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=0, verbose_name='\u7248\u6743\u6240\u6709\u4eba')),
                ('type', models.CharField(default='ruby', max_length=128)),
                ('effort', models.IntegerField(default=0, verbose_name='1000\u70b9\u51fa\u4e00\u4e2aruby')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(default=0, verbose_name='\u4f5c\u8005')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('work_hour', models.IntegerField(default=0, verbose_name='\u521b\u4f5c\u65f6\u957f')),
                ('effort', models.IntegerField(default=0)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
